#!/bin/bash

### DEPENDS ON ###
    # "surfraw"-for keyword based search,
### CONFIGURATION ###
    # place your browser in BROWSER=? line
    ## only if not using w3m 
	# you can use your bookmarks text file with 1 url/line, put it in second "BOOKMARKS=?" field replacing /tmp/bookmarks, comment out first "BOOKMARKS=?" line & grep -o line
    # w3m users do not need to change BOOKMARKS=?
    # default script uses rofi, to use dmenu uncomment the line starting with dmenu and comment out previous line starting with rofi
### USE ###
    # enter text in rofi/dmenu field, it will be matched against bookmarks, <enter> to open selected bookmark
    # to search specific sites use keyword as first argument ( like go for google, wi for wikipedia, aw for archwiki etc.) > read the script to find out all keywords
    # if no keyword or url is used, entire argument will be searched with duckduckgo
    # url is identified with http/www/org/com/edu/in etc., for other urls use ">" as keyword elsed it will go to duckduckgo
    # to use enterd text directly (not the matching bookmark) use <C-enter> (rofi only)
    # to edit selected bookmark use <C-space> (rofi only)

BROWSER=lariza
# only for w3m bookmarks/ comment out if not using w3m
BOOKMARKS=~/.w3m/bookmark.html
HISTORY=~/.w3m/history

# convert .w3m/bookmarks to simple text with 1 url/line; comment out if not using w3m
grep -o 'http[^"]*' $BOOKMARKS > /tmp/bookmarks
# add w3m history to the list of bookmarks
# grep -o 'http[^"]*' $HISTORY >> /tmp/bookmarks

shopt -s lastpipe
# add your plain text bookmarks here (do not edit or comment out if using w3m bookmarks)
BOOKMARKS=/tmp/bookmarks
rofi -dmenu -location 1 -l 10 -width 100 -p $BROWSER: < "$BOOKMARKS" | read url opts
# dmenu -l 10 -p $BROWSER: < "$BOOKMARKS" | read url opts

[[ ! $url ]] && exit

case $url in
	http*)   $BROWSER $url ;;
	\>)      $BROWSER $opts ;;
	*www.*)  $BROWSER $url ;;
	*.com*)  $BROWSER $url ;;
	*.in*)   $BROWSER $url ;;
	*.edu*)  $BROWSER $url ;;
	*.org*)  $BROWSER $url ;;
	aw)      archwiki    -browser=$BROWSER $opts ;;
	wi)      wikipedia   -browser=$BROWSER $opts ;;
	imdb)    imdb        -browser=$BROWSER $opts ;;
	aur)     aur         -browser=$BROWSER $opts ;;
	pkg)     archpkg     -browser=$BROWSER $opts ;;
	google)  google      -browser=$BROWSER $opts ;;
	yt)      youtube     -browser=$BROWSER $opts ;;
	ebay)    ebay        -browser=$BROWSER $opts ;;
	pubmed)  pubmed      -browser=$BROWSER $opts ;;
	git)	 github      -browser=$BROWSER $opts ;;
#	*)       qddg  $url $opts ;;
	*)	 duckduckgo  -browser=$BROWSER $url $opts ;;
esac
