#!/bin/bash

 grep -o 'http[^"]*' .w3m/bookmark.html > /tmp/bookmarks
 cat .w3m/history >> /tmp/bookmarks


 LAUNCHER='dmenu -p Bookmarks:'
 BROWSER='sakura -e w3m'
 BOOKMARKS="/tmp/bookmarks"

 url=`cat $BOOKMARKS | $LAUNCHER | awk -F '|' '{printf("%s ", $NF)}' | tr -d '\r\n'`

 if [ ${#url} -gt 0 ]
 then
 $BROWSER $url
 fi
