#!/bin/bash                                                                     
                                                                                
x=$@                                                                            
w3m "https://duckduckgo.com/?q=${x// /+}" 
