#!/bin/bash

    ## requires surfraw, w3m, sakura, dmenu/rofi aliased to dmenu
    ## add below to your .bashrc, (required to search with surfraw)
    ## PATH=/usr/lib/surfraw:${PATH}

    grep -o 'http[^"]*' .w3m/bookmark.html > /tmp/bookmarks
    grep -o 'http[^"]*' .w3m/history >> /tmp/bookmarks

    cat /tmp/bookmarks | dmenu -location 6 -lines 10 -width 100 -p 'W3M:' > /tmp/x

    check=$(wc -l < /tmp/x)
    (( check == 0)) && exit

    awk '{ print $1 }' /tmp/x > /tmp/y
    awk '{ print $2, $3, $4, $5, $6, $7, $8 }' /tmp/x > /tmp/z

    grep -o http /tmp/x && sakura -e w3m $(< /tmp/x) && exit
    grep -o "www\." /tmp/x && sakura -e w3m $(< /tmp/x) && exit
    grep -o "\.com" /tmp/x && sakura -e w3m $(< /tmp/x) && exit
    grep -o "\.in" /tmp/x && sakura -e w3m $(< /tmp/x) && exit
    grep -o "\.org" /tmp/x && sakura -e w3m $(< /tmp/x) && exit
    grep -o "\.edu" /tmp/x && sakura -e w3m $(< /tmp/x) && exit
....
    grep -o wiki /tmp/y && sakura -e wikipedia $(< /tmp/z) && exit
    grep -o imdb /tmp/y && sakura -e imdb $(< /tmp/z) && exit
    grep -o aur /tmp/y && sakura -e aur $(< /tmp/z) && exit
    grep -o aw /tmp/y && sakura -e archwiki $(< /tmp/z) && exit
    grep -o pkg /tmp/y && sakura -e archpkg $(< /tmp/z) && exit
    grep -o google /tmp/y && sakura -e google $(< /tmp/z) && exit
    grep -o dict /tmp/y && sakura -e webster $(< /tmp/z) && exit
    grep -o dictu /tmp/y && sakura -e urban $(< /tmp/z) && exit
    grep -o torrent /tmp/y && sakura -e piratebay $(< /tmp/z) && exit
    grep -o pubmed /tmp/y && sakura -e pubmed $(< /tmp/z) && exit

    sakura -e S $(< /tmp/x)
